export const GET_TEACHER_DASHBOARD_DATA_ACTION = "GET_TEACHER_DASHBOARD_DATA_ACTION";
export const GET_STUDENT_DASHBOARD_DATA_ACTION = "GET_STUDENT_DASHBOARD_DATA_ACTION";
export const GET_ADMIN_DASHBOARD_DATA_ACTION = "GET_ADMIN_DASHBOARD_DATA_ACTION";
