export const GET_STUDENT_ACTION = "SET_STUDENT_ACTION";
export const STUDENT_PAYMENT_CLASS_FEE = "STUDENT_PAYMENT_CLASS_FEE";
export const GET_STUDENT_TRANSACTIONS_ACTION = "GET_STUDENT_TRANSACTIONS_ACTION";
export const GET_STUDENT_TRANSACTIONS_BY_ID_ACTION = "GET_STUDENT_TRANSACTIONS_BY_ID_ACTION";

