export const SIGN_IN_ACTION = "SIGN_IN_ACTION";
export const SIGN_UP_ACTION = "SIGN_UP_ACTION";
export const SIGN_OUT_ACTION = "SIGN_OUT_ACTION";
export const FORGOT_PASSWORD_ACTION = "FORGOT_PASSWORD_ACTION";
