export const GET_LANDING_PAGE_DATA_ACTION = "GET_LANDING_PAGE_DATA_ACTION";
export const SET_LANDING_PAGE_DATA_ACTION = "SET_LANDING_PAGE_DATA_ACTION";
export const GET_LANDING_CLIENT_DATA_ACTION = "GET_LANDING_CLIENT_DATA_ACTION";
export const ADD_LANDING_CLIENT_DATA_ACTION = "ADD_LANDING_CLIENT_DATA_ACTION";