export const SET_USER_ACTION = "SET_USER_ACTION";
export const GET_USER_ACTION = "GET_USER_ACTION";
export const REMOVE_USER_REMOVE = "REMOVE_USER_ACTION";
export const SET_USER_DETAIL_ACTION = "SET_USER_DETAIL_ACTION";
export const GET_USER_DETIAL_ACTION = "GET_USER_DETIAL_ACTION";
export const REMOVE_USER_DETIAL_ACTION = "REMOVE_USER_DETIAL_ACTION";
